### ISSUE TITLE
Openspiel compilation error

### ISSUE THREAD

**Issue by brightyellow09** [indylab/tabular_xdo#3]
Hi！
Thanks for sharing and I'm working on tabular xdo recently.
When I tried to install openspiel and run "pip install -e ." at folder tabular_xdo/dependencies/open_spiel, the compilation process raise error like :
" tabular_xdo/dependencies/open_spiel/open_spiel/../open_spiel/game_parameters.h:146:22: error: explicit specialization of 'value' in class scope"
Would you mind give me some suggestion on this error?
Thanks a lot!

**Comment by JBLanier** [comment]
Hi there!

I've never seen this error before, but many similar errors are due to using a compiler that's too old. 
Generally, clang >= 7.0.0 has worked for us.
Try ensuring that you have clang 7.0.0 or above and using something like:
```
CC=clang CXX=clang++ pip install -e .
```

There are also a lot of compilation issues raised in the original DeepMind OpenSpiel repo that may be helpful as well.

**Comment by brightyellow09** [comment]
Ah, it's useful to use clang++-9, thanks a lot!
